---
- name: config_squid | Configuring Squid
  template:
    src: etc/squid/squid.conf.j2
    dest: "{{ squid_root_dir+'/squid.conf' }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "restart {{ squid_service }}"
