---
- name: redhat | Installing Squid (Non-Fedora)
  yum:
    name: "{{ squid_package }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Squid (Fedora)
  dnf:
    name: "{{ squid_package }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"
